### ISSUE TITLE
uploading stops at 100% and  nothing happens.

### ISSUE THREAD

**Issue by usgold** [Onihani/filepond-php-server-example#2]
![Zrzut ekranu 2021-09-26 o 20 36 47](https://user-images.githubusercontent.com/18323102/134819947-77294e17-e657-45a0-822d-2b4897aed631.png)

**Comment by onihani** [comment]
@usgold Thanks for the update on the issue. I have noticed it too i would do well to fix it ASAP

**Comment by onihani** [comment]
@usgold  the issue has been solved now. You update (pull the latest changes) you local code and test again. Or see the working update live [here](http://www.ics-courses.co.uk/natbongo/filepond-php-server-example/)

**Comment by usgold** [comment]
On your server issue seems to be solved but on my side still the same situation.

Upload cannot complete. 

Do you have any suggestions what can cause this?

Best regards 

Norbert

**Comment by onihani** [comment]
@usgold, The issue was caused in [util/read_write_functions.php on line 11](https://github.com/Onihani/filepond-php-server-example/commit/719835f284dbb4e51667cc1d1d83fe4faee459b5)

I removed JSON_PRETTY_PRINT

You can check out the commit and update the necessary changes in your code locally or pull the latest changes and test again

**Comment by onihani** [comment]
@usgold  **IMPORTANT**, also set the contents of **database.json** to an empty array

**Comment by usgold** [comment]
I checked both things and still the same 

I see preview of the image but upload stops at 100% and nothing…

**Comment by onihani** [comment]
@usgold please could you send a screenshot of the console logs in your browser console when this happens

**Comment by usgold** [comment]
Thanks for suggestion, 

I have changed the defaulf PHP 5 to PHP 7 and nowi it works fine (attached console log (previously I had error 500)  … except i cannot find the uploaded file … (I have not changed config.php so scripts should create tmp and image directory, but it does not happen

**Comment by usgold** [comment]
When I create directories tmp and images myself the situation comes back (100% and stop – nothing happens)

Please see another screeen with console log

**Comment by usgold** [comment]
Missed attachement with console log from previous email

**Comment by onihani** [comment]
@usgold the attach images seem to be missing please could you resend them or alternatively you could re-clone the repo into another directory and try

**Comment by usgold** [comment]
I hope this printscreen is attached  now.

I do not have the directory tmp and images …. And see this
